### ISSUE TITLE
Offline use?

### ISSUE THREAD

**Issue by luixal** [Pagebakers/meteor-ionicons#10]
Just right now, ionicons CDN is down... any way to make this package work loading font from local?

Thanks!

**Comment by Pagebakers** [comment]
You could include the script in your project and host the files yourself on CDN or locally pretty easily. It's quite basic.
```js
var head = document.getElementsByTagName('head')[0];
var s = document.createElement('link');

s.type = 'text/css';
s.rel = 'stylesheet';
s.href = '//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css';
head.appendChild(s);
```

Don't really have plans to add more functionality to the plugin.

Happy to except pull requests for local font support through.

**Comment by tripflex** [comment]
Look at this example that uses the npm version, and uses those files, which would work for offline use, just would need to update it to work that way:

https://github.com/DAB0mB/meteor-npm-ionic/blob/master/package.js

**Comment by tripflex** [comment]
@luixal I actually created a package for ionicons 3 that works for offline use:

http://github.com/tripflex/meteor-ionicons3

**Comment by luixal** [comment]
Seems great @tripflex . Will give it a try, thanks!
