### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by NilsDannemann** [Pagebakers/meteor-ionicons#5]
After adding the package to my meteor project I'm getting the following errors a bunch of times in chrome:
<pre><code>Failed to decode downloaded font: ...</code></pre>

The Icons are visible in chrome, but the error remains.

Sample Project:
http://workstreams_v3.meteor.com/

The error is gone, when I manually add the ionicons css to the hearder:
\<link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

But that shouldn't really be necessary, right?
Can/Should I just ignore the error?

**Comment by Pagebakers** [comment]
see https://github.com/Pagebakers/meteor-ionicons/issues/6
