### ISSUE TITLE
Fonts rejected by Firefox font sanitizer

### ISSUE THREAD

**Issue by raihle** [Pagebakers/meteor-ionicons#6]
Firefox produces the following error in its developer console:

    downloadable font: rejected by sanitizer (font-family: ionicons" style:normal weight:normal stretch:normal src index:1)
    source: https://www.example.com/packages/ionicons/fonts/ionicons.ttf
    downloadable font: rejected by sanitizer (font-family: ionicons" style:normal weight:normal stretch:normal src index:2)
    source: https://www.example.com/packages/ionicons/fonts/ionicons.woff

On Windows 8.1/Firefox 38, the font icons are still displayed correctly. On Ubuntu 14.04/Firefox 35, they instead show as boxes with character codes. To be clear, the message is shown on both systems.

In the Firefox Network inspector it seems like the fonts are being served with a text/html content-type header.

I have worked around this by removing this package and serving the font files from my `public` directory, which caused them to be served with a better content-type (application/x-font-ttf) and display correctly on both systems.

**Comment by Pagebakers** [comment]
For production environments it's advisable to load the fonts from CDN anyway. I'll see if I can make an update for this soon. Thanks!

**Comment by Pagebakers** [comment]
Updated the package to 2.0.1 and now loading the fonts using CDN.

**Comment by raihle** [comment]
It doesn't seem to be working at all after the update - the stylesheet link is not being inserted anywhere. Simply adding your package.html to my project works fine, but adding the package itself seems to have no effect. I tried this in a new project with the same result. Perhaps there is a missing package dependency?

**Comment by Pagebakers** [comment]
I was expecting meteor to add links to external css files automatically to the head also, like script tags. But that doesn't seem to work, I published a fix.

Please update to 2.0.1-1

**Comment by fullhdpixel** [comment]
Before the update I had 7 errors, now I have 2 left:

Failed to decode downloaded font: http://localhost:4000/packages/ionicons/fonts/ionicons.ttf
app:1 Failed to decode downloaded font: http://localhost:4000/packages/ionicons/fonts/ionicons.woff
